### ISSUE TITLE
Adding Pololu 3pi Robot Library to Arduino

### ISSUE THREAD

**Issue by spdale** [sdale28/Pololu-Arduino-Library#1]
Hi there @per1234. This is the continued discussion from https://github.com/arduino/Arduino/issues/5340 

Look, I may be a super idiot, but I can't get https://www.pololu.com/file/download/libpololu-arduino-150324.zip?file_id=0J868 to work for me. Any way I try to add it to my Arduino libraries, I get the following error: 

```
Arduino: 1.6.11 (Mac OS X), Board: "Arduino/Genuino Uno"

Specified folder/zip file does not contain a valid library
```

I also wasn't able to `#include` any of the library resources if I added the unzipped folder to my `Documents/Arduino/hardware` folder.

To add it, I go `Sketch > Include Library > Add .ZIP Library` and it always throws the invalid library error.

So since I'm a noob and couldn't get it to work, I repeated exactly what I saw worked in the Makeblock library found here: https://github.com/Makeblock-official/Makeblock-Libraries

I figured my modified library would be helpful for other people too, which is why I brought it up at https://github.com/arduino/Arduino/issues/5340 

Thanks for the help.

**Comment by per1234** [comment]
The problem is it's not a library, it's a hardware package so trying to install it via Sketch > Include Library > Add .ZIP Library won't work. It does contain the libraries bundled with the hardware package so when you install the hardware the libraries are installed also. They will only show up in the File > Examples menu when you have one of the Oragutan/3pi boards selected from Tools > Board menu. To install it follow the instructions at https://www.pololu.com/docs/0J17/3.

I don't own one of these robots so I can't actually test it on the hardware but the installation does work for me and it will compile.

**Comment by spdale** [comment]
You know what? You're totally right. What threw me previously was that you have to have the `Pololu Orangutan or 3pi robot w/ ATmega328P` board selected in order to see Pololu's examples. Got'cha. Personally, I don't find this very intuitive (I'd like the examples to always be present), but I guess it makes sense for the IDE.

Thanks for all the help!

**Comment by per1234** [comment]
Glad I was able to help. I like your spirit of contributing to the community. Arduino provides lots of opportunities to contribute, even for people without a lot of experience. If we all give back just a little it really adds up to something amazing!
